using ReportEngine.Core;
using Xunit;

namespace ReportEngine.Core.Tests;

/// <summary>
/// ReportElement 基类属性测试（通过 TextElement 测试继承属性）
/// </summary>
public class ReportElementBaseTests
{
    // ============== Id ==============

    [Fact]
    public void Id_AutoGenerated()
    {
        var el = new TextElement();
        Assert.NotNull(el.Id);
        Assert.NotEmpty(el.Id);
    }

    [Fact]
    public void Id_Unique()
    {
        var el1 = new TextElement();
        var el2 = new TextElement();
        Assert.NotEqual(el1.Id, el2.Id);
    }

    [Fact]
    public void Id_SetCustom_Works()
    {
        var el = new TextElement { Id = "custom-id" };
        Assert.Equal("custom-id", el.Id);
    }

    // ============== Name ==============

    [Fact]
    public void Name_NullByDefault()
    {
        var el = new TextElement();
        Assert.Null(el.Name);
    }

    [Fact]
    public void Name_Set_Works()
    {
        var el = new TextElement { Name = "txtTitle" };
        Assert.Equal("txtTitle", el.Name);
    }

    // ============== GroupId ==============

    [Fact]
    public void GroupId_NullByDefault()
    {
        var el = new TextElement();
        Assert.Null(el.GroupId);
    }

    [Fact]
    public void GroupId_Set_Works()
    {
        var el = new TextElement { GroupId = "group1" };
        Assert.Equal("group1", el.GroupId);
    }

    // ============== X/Y ==============

    [Fact]
    public void X_DefaultIsZero()
    {
        var el = new TextElement();
        Assert.Equal(0, el.X);
    }

    [Fact]
    public void Y_DefaultIsZero()
    {
        var el = new TextElement();
        Assert.Equal(0, el.Y);
    }

    [Fact]
    public void X_Set_Works()
    {
        var el = new TextElement { X = 50.5 };
        Assert.Equal(50.5, el.X);
    }

    [Fact]
    public void Y_Set_Works()
    {
        var el = new TextElement { Y = 25.3 };
        Assert.Equal(25.3, el.Y);
    }

    // ============== Width/Height ==============

    [Fact]
    public void Width_DefaultIsZero()
    {
        var el = new TextElement();
        Assert.Equal(0, el.Width);
    }

    [Fact]
    public void Height_DefaultIsZero()
    {
        var el = new TextElement();
        Assert.Equal(0, el.Height);
    }

    [Fact]
    public void Width_Set_Works()
    {
        var el = new TextElement { Width = 100 };
        Assert.Equal(100, el.Width);
    }

    [Fact]
    public void Height_Set_Works()
    {
        var el = new TextElement { Height = 20 };
        Assert.Equal(20, el.Height);
    }

    // ============== BackgroundColor ==============

    [Fact]
    public void BackgroundColor_NullByDefault()
    {
        var el = new TextElement();
        Assert.Null(el.BackgroundColor);
    }

    [Fact]
    public void BackgroundColor_Set_Works()
    {
        var el = new TextElement { BackgroundColor = "#FFFF00" };
        Assert.Equal("#FFFF00", el.BackgroundColor);
    }

    // ============== Border ==============

    [Fact]
    public void Border_NullByDefault()
    {
        var el = new TextElement();
        Assert.Null(el.Border);
    }

    [Fact]
    public void Border_Set_Works()
    {
        var el = new TextElement
        {
            Border = new BorderDef { Width = 2, Color = "#FF0000" }
        };
        Assert.NotNull(el.Border);
        Assert.Equal(2, el.Border.Width);
    }

    // ============== Visible ==============

    [Fact]
    public void Visible_TrueByDefault()
    {
        var el = new TextElement();
        Assert.True(el.Visible);
    }

    [Fact]
    public void Visible_SetFalse_Works()
    {
        var el = new TextElement { Visible = false };
        Assert.False(el.Visible);
    }

    // ============== VisibleExpression ==============

    [Fact]
    public void VisibleExpression_NullByDefault()
    {
        var el = new TextElement();
        Assert.Null(el.VisibleExpression);
    }

    [Fact]
    public void VisibleExpression_Set_Works()
    {
        var el = new TextElement { VisibleExpression = "[ShowDetails] == true" };
        Assert.Contains("ShowDetails", el.VisibleExpression);
    }

    // ============== Locked ==============

    [Fact]
    public void Locked_FalseByDefault()
    {
        var el = new TextElement();
        Assert.False(el.Locked);
    }

    [Fact]
    public void Locked_SetTrue_Works()
    {
        var el = new TextElement { Locked = true };
        Assert.True(el.Locked);
    }

    // ============== Rotation ==============

    [Fact]
    public void Rotation_DefaultIsZero()
    {
        var el = new TextElement();
        Assert.Equal(0, el.Rotation);
    }

    [Fact]
    public void Rotation_Set90_Works()
    {
        var el = new TextElement { Rotation = 90 };
        Assert.Equal(90, el.Rotation);
    }

    [Fact]
    public void Rotation_Set45_Works()
    {
        var el = new TextElement { Rotation = 45 };
        Assert.Equal(45, el.Rotation);
    }

    [Fact]
    public void Rotation_SetNegative_Works()
    {
        var el = new TextElement { Rotation = -30 };
        Assert.Equal(-30, el.Rotation);
    }

    // ============== Opacity ==============

    [Fact]
    public void Opacity_DefaultIs1()
    {
        var el = new TextElement();
        Assert.Equal(1.0, el.Opacity);
    }

    [Fact]
    public void Opacity_SetHalf_Works()
    {
        var el = new TextElement { Opacity = 0.5 };
        Assert.Equal(0.5, el.Opacity);
    }

    [Fact]
    public void Opacity_SetZero_Works()
    {
        var el = new TextElement { Opacity = 0 };
        Assert.Equal(0, el.Opacity);
    }

    // ============== ConditionalFormats ==============

    [Fact]
    public void ConditionalFormats_EmptyByDefault()
    {
        var el = new TextElement();
        Assert.NotNull(el.ConditionalFormats);
        Assert.Empty(el.ConditionalFormats);
    }

    [Fact]
    public void ConditionalFormats_Add_Works()
    {
        var el = new TextElement();
        el.ConditionalFormats.Add(new ConditionalFormatRule
        {
            Expression = "[Value] > 100",
            BackgroundColor = "#FF0000"
        });
        Assert.Single(el.ConditionalFormats);
    }

    [Fact]
    public void ConditionalFormats_AddMultiple_Works()
    {
        var el = new TextElement();
        el.ConditionalFormats.Add(new ConditionalFormatRule { Expression = "[A] > 1" });
        el.ConditionalFormats.Add(new ConditionalFormatRule { Expression = "[A] > 2" });
        Assert.Equal(2, el.ConditionalFormats.Count);
    }

    // ============== 综合场景 ==============

    [Fact]
    public void ReportElement_FullSetup_Works()
    {
        var el = new TextElement
        {
            Id = "el-001",
            Name = "txtAmount",
            GroupId = "grp1",
            X = 10,
            Y = 20,
            Width = 100,
            Height = 25,
            BackgroundColor = "#EEEEEE",
            Border = new BorderDef { Width = 1, Top = true, Bottom = true },
            Visible = true,
            Locked = true,
            Rotation = 0,
            Opacity = 0.8
        };

        Assert.Equal("el-001", el.Id);
        Assert.Equal("txtAmount", el.Name);
        Assert.Equal("grp1", el.GroupId);
        Assert.Equal(10, el.X);
        Assert.Equal(20, el.Y);
        Assert.Equal(100, el.Width);
        Assert.Equal(25, el.Height);
        Assert.True(el.Locked);
        Assert.Equal(0.8, el.Opacity);
    }
}

/// <summary>
/// ImageElement 高级属性测试
/// </summary>
public class ImageElementAdvancedTests
{
    // ============== Source ==============

    [Fact]
    public void Source_EmptyByDefault()
    {
        var el = new ImageElement();
        Assert.Equal("", el.Source);
    }

    [Fact]
    public void Source_SetPath_Works()
    {
        var el = new ImageElement { Source = @"C:\images\logo.png" };
        Assert.Contains("logo.png", el.Source);
    }

    [Fact]
    public void Source_SetUrl_Works()
    {
        var el = new ImageElement { Source = "https://example.com/logo.png" };
        Assert.StartsWith("https://", el.Source);
    }

    [Fact]
    public void Source_SetBase64_Works()
    {
        var el = new ImageElement { Source = "data:image/png;base64,iVBOR..." };
        Assert.StartsWith("data:", el.Source);
    }

    [Fact]
    public void Source_SetExpression_Works()
    {
        var el = new ImageElement { Source = "{{currentRow.PhotoUrl}}" };
        Assert.Contains("{{", el.Source);
    }

    // ============== Sizing ==============

    [Fact]
    public void Sizing_DefaultIsFitProportional()
    {
        var el = new ImageElement();
        Assert.Equal(ImageSizing.FitProportional, el.Sizing);
    }

    [Fact]
    public void Sizing_SetStretch_Works()
    {
        var el = new ImageElement { Sizing = ImageSizing.Stretch };
        Assert.Equal(ImageSizing.Stretch, el.Sizing);
    }

    [Fact]
    public void Sizing_SetClip_Works()
    {
        var el = new ImageElement { Sizing = ImageSizing.Clip };
        Assert.Equal(ImageSizing.Clip, el.Sizing);
    }

    [Fact]
    public void Sizing_SetActualSize_Works()
    {
        var el = new ImageElement { Sizing = ImageSizing.ActualSize };
        Assert.Equal(ImageSizing.ActualSize, el.Sizing);
    }

    [Fact]
    public void Sizing_CanBeChanged()
    {
        var el = new ImageElement { Sizing = ImageSizing.FitProportional };
        el.Sizing = ImageSizing.Stretch;
        Assert.Equal(ImageSizing.Stretch, el.Sizing);
    }

    // ============== 综合场景 ==============

    [Fact]
    public void ImageElement_LogoSetup_Works()
    {
        var el = new ImageElement
        {
            Source = "logo.png",
            X = 10,
            Y = 5,
            Width = 50,
            Height = 20,
            Sizing = ImageSizing.FitProportional
        };

        Assert.Equal("logo.png", el.Source);
        Assert.Equal(ImageSizing.FitProportional, el.Sizing);
    }

    [Fact]
    public void ImageElement_DynamicSource_Works()
    {
        var el = new ImageElement
        {
            Source = "{{currentRow.PhotoUrl}}",
            Sizing = ImageSizing.Stretch,
            Width = 80,
            Height = 80
        };

        Assert.Contains("{{", el.Source);
        Assert.Equal(ImageSizing.Stretch, el.Sizing);
    }
}

/// <summary>
/// LineElement 高级属性测试
/// </summary>
public class LineElementAdvancedTests
{
    // ============== Direction ==============

    [Fact]
    public void Direction_DefaultIsHorizontal()
    {
        var el = new LineElement();
        Assert.Equal(LineDirection.Horizontal, el.Direction);
    }

    [Fact]
    public void Direction_SetVertical_Works()
    {
        var el = new LineElement { Direction = LineDirection.Vertical };
        Assert.Equal(LineDirection.Vertical, el.Direction);
    }

    [Fact]
    public void Direction_SetDiagonal_Works()
    {
        var el = new LineElement { Direction = LineDirection.Diagonal };
        Assert.Equal(LineDirection.Diagonal, el.Direction);
    }

    [Fact]
    public void Direction_CanBeChanged()
    {
        var el = new LineElement { Direction = LineDirection.Horizontal };
        el.Direction = LineDirection.Vertical;
        Assert.Equal(LineDirection.Vertical, el.Direction);
    }

    // ============== LineWidth ==============

    [Fact]
    public void LineWidth_DefaultIs1()
    {
        var el = new LineElement();
        Assert.Equal(1, el.LineWidth);
    }

    [Fact]
    public void LineWidth_Set_Works()
    {
        var el = new LineElement { LineWidth = 2.5 };
        Assert.Equal(2.5, el.LineWidth);
    }

    [Fact]
    public void LineWidth_SetThin_Works()
    {
        var el = new LineElement { LineWidth = 0.5 };
        Assert.Equal(0.5, el.LineWidth);
    }

    [Fact]
    public void LineWidth_SetThick_Works()
    {
        var el = new LineElement { LineWidth = 5 };
        Assert.Equal(5, el.LineWidth);
    }

    // ============== LineColor ==============

    [Fact]
    public void LineColor_DefaultIsBlack()
    {
        var el = new LineElement();
        Assert.Equal("#000000", el.LineColor);
    }

    [Fact]
    public void LineColor_SetRed_Works()
    {
        var el = new LineElement { LineColor = "#FF0000" };
        Assert.Equal("#FF0000", el.LineColor);
    }

    [Fact]
    public void LineColor_SetGray_Works()
    {
        var el = new LineElement { LineColor = "#CCCCCC" };
        Assert.Equal("#CCCCCC", el.LineColor);
    }

    [Fact]
    public void LineColor_CanBeChanged()
    {
        var el = new LineElement { LineColor = "#000000" };
        el.LineColor = "#0000FF";
        Assert.Equal("#0000FF", el.LineColor);
    }

    // ============== 综合场景 ==============

    [Fact]
    public void LineElement_HorizontalSeparator_Works()
    {
        var el = new LineElement
        {
            Direction = LineDirection.Horizontal,
            LineWidth = 1,
            LineColor = "#CCCCCC",
            X = 0,
            Y = 50,
            Width = 210
        };

        Assert.Equal(LineDirection.Horizontal, el.Direction);
        Assert.Equal(210, el.Width);
    }

    [Fact]
    public void LineElement_VerticalDivider_Works()
    {
        var el = new LineElement
        {
            Direction = LineDirection.Vertical,
            LineWidth = 0.5,
            LineColor = "#999999",
            X = 105,
            Y = 0,
            Height = 297
        };

        Assert.Equal(LineDirection.Vertical, el.Direction);
    }

    [Fact]
    public void LineElement_ThickRedLine_Works()
    {
        var el = new LineElement
        {
            LineWidth = 3,
            LineColor = "#FF0000",
            Width = 100
        };

        Assert.Equal(3, el.LineWidth);
        Assert.Equal("#FF0000", el.LineColor);
    }
}

/// <summary>
/// ShapeElement 高级属性测试
/// </summary>
public class ShapeElementAdvancedTests
{
    // ============== Shape ==============

    [Fact]
    public void Shape_DefaultIsRectangle()
    {
        var el = new ShapeElement();
        Assert.Equal(ShapeType.Rectangle, el.Shape);
    }

    [Fact]
    public void Shape_SetEllipse_Works()
    {
        var el = new ShapeElement { Shape = ShapeType.Ellipse };
        Assert.Equal(ShapeType.Ellipse, el.Shape);
    }

    [Fact]
    public void Shape_SetRoundedRect_Works()
    {
        var el = new ShapeElement { Shape = ShapeType.RoundedRect };
        Assert.Equal(ShapeType.RoundedRect, el.Shape);
    }

    [Fact]
    public void Shape_SetTriangle_Works()
    {
        var el = new ShapeElement { Shape = ShapeType.Triangle };
        Assert.Equal(ShapeType.Triangle, el.Shape);
    }

    [Fact]
    public void Shape_CanBeChanged()
    {
        var el = new ShapeElement { Shape = ShapeType.Rectangle };
        el.Shape = ShapeType.Ellipse;
        Assert.Equal(ShapeType.Ellipse, el.Shape);
    }

    // ============== BorderRadius ==============

    [Fact]
    public void BorderRadius_DefaultIsZero()
    {
        var el = new ShapeElement();
        Assert.Equal(0, el.BorderRadius);
    }

    [Fact]
    public void BorderRadius_Set_Works()
    {
        var el = new ShapeElement { BorderRadius = 5 };
        Assert.Equal(5, el.BorderRadius);
    }

    [Fact]
    public void BorderRadius_SetLarge_Works()
    {
        var el = new ShapeElement { BorderRadius = 20 };
        Assert.Equal(20, el.BorderRadius);
    }

    // ============== FillColor ==============

    [Fact]
    public void FillColor_DefaultIsWhite()
    {
        var el = new ShapeElement();
        Assert.Equal("#FFFFFF", el.FillColor);
    }

    [Fact]
    public void FillColor_SetBlue_Works()
    {
        var el = new ShapeElement { FillColor = "#0000FF" };
        Assert.Equal("#0000FF", el.FillColor);
    }

    [Fact]
    public void FillColor_SetLightGray_Works()
    {
        var el = new ShapeElement { FillColor = "#F0F0F0" };
        Assert.Equal("#F0F0F0", el.FillColor);
    }

    [Fact]
    public void FillColor_CanBeChanged()
    {
        var el = new ShapeElement { FillColor = "#FFFFFF" };
        el.FillColor = "#FF0000";
        Assert.Equal("#FF0000", el.FillColor);
    }

    // ============== 综合场景 ==============

    [Fact]
    public void ShapeElement_RoundedBox_Works()
    {
        var el = new ShapeElement
        {
            Shape = ShapeType.RoundedRect,
            BorderRadius = 8,
            FillColor = "#E3F2FD",
            Width = 100,
            Height = 40
        };

        Assert.Equal(ShapeType.RoundedRect, el.Shape);
        Assert.Equal(8, el.BorderRadius);
        Assert.Equal("#E3F2FD", el.FillColor);
    }

    [Fact]
    public void ShapeElement_Circle_Works()
    {
        var el = new ShapeElement
        {
            Shape = ShapeType.Ellipse,
            FillColor = "#FF5722",
            Width = 50,
            Height = 50
        };

        Assert.Equal(ShapeType.Ellipse, el.Shape);
        Assert.Equal(50, el.Width);
        Assert.Equal(50, el.Height);
    }

    [Fact]
    public void ShapeElement_BackgroundRect_Works()
    {
        var el = new ShapeElement
        {
            Shape = ShapeType.Rectangle,
            FillColor = "#F5F5F5",
            X = 0,
            Y = 0,
            Width = 210,
            Height = 297
        };

        Assert.Equal(ShapeType.Rectangle, el.Shape);
        Assert.Equal(210, el.Width);
        Assert.Equal(297, el.Height);
    }
}
