using ReportEngine.Core;
using Xunit;

namespace ReportEngine.Core.Tests;

/// <summary>
/// ReportElement 基类行为测试：
///   - 默认值
///   - Id 自动生成
///   - 位置/尺寸
///   - 可见性
///   - 锁定/旋转/透明度
///   - 条件格式
/// </summary>
public class ReportElementBehaviorTests
{
    // ============== 默认值 ==============

    [Fact]
    public void Constructor_DefaultValues_AreCorrect()
    {
        var el = new TestReportElement();

        Assert.NotNull(el.Id);
        Assert.NotEmpty(el.Id);
        Assert.Null(el.Name);
        Assert.Null(el.GroupId);
        Assert.Equal(0, el.X);
        Assert.Equal(0, el.Y);
        Assert.Equal(0, el.Width);
        Assert.Equal(0, el.Height);
        Assert.Null(el.BackgroundColor);
        Assert.Null(el.Border);
        Assert.True(el.Visible);
        Assert.Null(el.VisibleExpression);
        Assert.False(el.Locked);
        Assert.Equal(0, el.Rotation);
        Assert.Equal(1.0, el.Opacity);
        Assert.NotNull(el.ConditionalFormats);
        Assert.Empty(el.ConditionalFormats);
    }

    // ============== Id ==============

    [Fact]
    public void Id_AutoGenerated_NotEmpty()
    {
        var el = new TestReportElement();
        Assert.NotNull(el.Id);
        Assert.NotEmpty(el.Id);
    }

    [Fact]
    public void Id_AutoGenerated_Unique()
    {
        var el1 = new TestReportElement();
        var el2 = new TestReportElement();
        Assert.NotEqual(el1.Id, el2.Id);
    }

    [Fact]
    public void Id_CanBeSet()
    {
        var el = new TestReportElement { Id = "custom-id" };
        Assert.Equal("custom-id", el.Id);
    }

    // ============== Name ==============

    [Fact]
    public void Name_NullByDefault()
    {
        var el = new TestReportElement();
        Assert.Null(el.Name);
    }

    [Fact]
    public void Name_SetAndGet_Works()
    {
        var el = new TestReportElement { Name = "header" };
        Assert.Equal("header", el.Name);
    }

    [Fact]
    public void Name_ChineseCharacters_Works()
    {
        var el = new TestReportElement { Name = "标题文本" };
        Assert.Equal("标题文本", el.Name);
    }

    // ============== GroupId ==============

    [Fact]
    public void GroupId_NullByDefault()
    {
        var el = new TestReportElement();
        Assert.Null(el.GroupId);
    }

    [Fact]
    public void GroupId_SetAndGet_Works()
    {
        var el = new TestReportElement { GroupId = "group1" };
        Assert.Equal("group1", el.GroupId);
    }

    // ============== X/Y/Width/Height ==============

    [Fact]
    public void Position_SetAndGet_Works()
    {
        var el = new TestReportElement { X = 10, Y = 20, Width = 100, Height = 50 };
        Assert.Equal(10, el.X);
        Assert.Equal(20, el.Y);
        Assert.Equal(100, el.Width);
        Assert.Equal(50, el.Height);
    }

    [Fact]
    public void Position_DecimalValues_Works()
    {
        var el = new TestReportElement { X = 10.5, Y = 20.75, Width = 100.25, Height = 50.125 };
        Assert.Equal(10.5, el.X);
        Assert.Equal(20.75, el.Y);
        Assert.Equal(100.25, el.Width);
        Assert.Equal(50.125, el.Height);
    }

    [Fact]
    public void Position_CanBeModified()
    {
        var el = new TestReportElement { X = 10, Y = 20 };
        el.X = 30;
        el.Y = 40;
        Assert.Equal(30, el.X);
        Assert.Equal(40, el.Y);
    }

    // ============== BackgroundColor ==============

    [Fact]
    public void BackgroundColor_NullByDefault()
    {
        var el = new TestReportElement();
        Assert.Null(el.BackgroundColor);
    }

    [Fact]
    public void BackgroundColor_SetHex_Works()
    {
        var el = new TestReportElement { BackgroundColor = "#FF0000" };
        Assert.Equal("#FF0000", el.BackgroundColor);
    }

    [Fact]
    public void BackgroundColor_SetWithAlpha_Works()
    {
        var el = new TestReportElement { BackgroundColor = "#80FF0000" };
        Assert.Equal("#80FF0000", el.BackgroundColor);
    }

    [Fact]
    public void BackgroundColor_CanBeCleared()
    {
        var el = new TestReportElement { BackgroundColor = "#FF0000" };
        el.BackgroundColor = null;
        Assert.Null(el.BackgroundColor);
    }

    // ============== Border ==============

    [Fact]
    public void Border_NullByDefault()
    {
        var el = new TestReportElement();
        Assert.Null(el.Border);
    }

    [Fact]
    public void Border_SetAndGet_Works()
    {
        var border = new BorderDef { Width = 2, Color = "#000000" };
        var el = new TestReportElement { Border = border };
        Assert.Same(border, el.Border);
    }

    // ============== Visible ==============

    [Fact]
    public void Visible_TrueByDefault()
    {
        var el = new TestReportElement();
        Assert.True(el.Visible);
    }

    [Fact]
    public void Visible_SetFalse_Works()
    {
        var el = new TestReportElement { Visible = false };
        Assert.False(el.Visible);
    }

    [Fact]
    public void Visible_CanBeToggled()
    {
        var el = new TestReportElement { Visible = true };
        el.Visible = false;
        Assert.False(el.Visible);
    }

    // ============== VisibleExpression ==============

    [Fact]
    public void VisibleExpression_NullByDefault()
    {
        var el = new TestReportElement();
        Assert.Null(el.VisibleExpression);
    }

    [Fact]
    public void VisibleExpression_SetAndGet_Works()
    {
        var el = new TestReportElement { VisibleExpression = "[ShowHeader] = true" };
        Assert.Equal("[ShowHeader] = true", el.VisibleExpression);
    }

    // ============== Locked ==============

    [Fact]
    public void Locked_FalseByDefault()
    {
        var el = new TestReportElement();
        Assert.False(el.Locked);
    }

    [Fact]
    public void Locked_SetTrue_Works()
    {
        var el = new TestReportElement { Locked = true };
        Assert.True(el.Locked);
    }

    // ============== Rotation ==============

    [Fact]
    public void Rotation_ZeroByDefault()
    {
        var el = new TestReportElement();
        Assert.Equal(0, el.Rotation);
    }

    [Fact]
    public void Rotation_Set90_Works()
    {
        var el = new TestReportElement { Rotation = 90 };
        Assert.Equal(90, el.Rotation);
    }

    [Fact]
    public void Rotation_Set180_Works()
    {
        var el = new TestReportElement { Rotation = 180 };
        Assert.Equal(180, el.Rotation);
    }

    [Fact]
    public void Rotation_Set270_Works()
    {
        var el = new TestReportElement { Rotation = 270 };
        Assert.Equal(270, el.Rotation);
    }

    [Fact]
    public void Rotation_SetDecimal_Works()
    {
        var el = new TestReportElement { Rotation = 45.5 };
        Assert.Equal(45.5, el.Rotation);
    }

    // ============== Opacity ==============

    [Fact]
    public void Opacity_DefaultIs1()
    {
        var el = new TestReportElement();
        Assert.Equal(1.0, el.Opacity);
    }

    [Fact]
    public void Opacity_SetHalf_Works()
    {
        var el = new TestReportElement { Opacity = 0.5 };
        Assert.Equal(0.5, el.Opacity);
    }

    [Fact]
    public void Opacity_SetZero_Works()
    {
        var el = new TestReportElement { Opacity = 0 };
        Assert.Equal(0, el.Opacity);
    }

    [Fact]
    public void Opacity_SetOne_Works()
    {
        var el = new TestReportElement { Opacity = 1.0 };
        Assert.Equal(1.0, el.Opacity);
    }

    // ============== ConditionalFormats ==============

    [Fact]
    public void ConditionalFormats_EmptyByDefault()
    {
        var el = new TestReportElement();
        Assert.Empty(el.ConditionalFormats);
    }

    [Fact]
    public void ConditionalFormats_Add_Works()
    {
        var el = new TestReportElement();
        el.ConditionalFormats.Add(new ConditionalFormatRule
        {
            Expression = "[Amount] > 1000",
            BackgroundColor = "#FF0000"
        });
        Assert.Single(el.ConditionalFormats);
    }

    [Fact]
    public void ConditionalFormats_AddMultiple_Works()
    {
        var el = new TestReportElement();
        el.ConditionalFormats.Add(new ConditionalFormatRule { Expression = "[Amount] > 1000" });
        el.ConditionalFormats.Add(new ConditionalFormatRule { Expression = "[Amount] < 100" });
        Assert.Equal(2, el.ConditionalFormats.Count);
    }

    // ============== 综合场景 ==============

    [Fact]
    public void ReportElement_FullSetup_Works()
    {
        var el = new TestReportElement
        {
            Name = "amount",
            GroupId = "group1",
            X = 10,
            Y = 20,
            Width = 100,
            Height = 30,
            BackgroundColor = "#EEEEEE",
            Border = new BorderDef { Width = 1 },
            Visible = true,
            Locked = false,
            Rotation = 0,
            Opacity = 0.8
        };
        el.ConditionalFormats.Add(new ConditionalFormatRule
        {
            Expression = "[Amount] > 1000",
            FontColor = "#FF0000",
            Bold = true
        });

        Assert.Equal("amount", el.Name);
        Assert.Equal("group1", el.GroupId);
        Assert.Equal(10, el.X);
        Assert.Equal(0.8, el.Opacity);
        Assert.Single(el.ConditionalFormats);
    }

    [Fact]
    public void ReportElement_InBand_Works()
    {
        var band = new Band { Type = BandType.Detail, Height = 50 };
        band.Elements.Add(new TestReportElement { Name = "field1", X = 10, Y = 5, Width = 80, Height = 20 });
        band.Elements.Add(new TestReportElement { Name = "field2", X = 100, Y = 5, Width = 80, Height = 20 });

        Assert.Equal(2, band.Elements.Count);
        Assert.Equal("field1", band.Elements[0].Name);
        Assert.Equal("field2", band.Elements[1].Name);
    }

    // ============== 辅助测试类 ==============

    private class TestReportElement : ReportElement
    {
    }
}
